import { NextResponse } from "next/server"

export async function GET(request: Request) {
  const url = new URL(request.url)
  const userId = url.searchParams.get("userId")
  const format = url.searchParams.get("format") || "txt"
  const isPremium = url.searchParams.get("premium") === "true"

  if (!isPremium && format === "pdf") {
    return NextResponse.json({ error: "PDF export requires Premium. Upgrade in Settings." }, { status: 403 })
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || ""
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || ""

  const res = await fetch(`${supabaseUrl}/rest/v1/trades?select=*&user_id=eq.${userId}&order=created_at.desc`, {
    headers: { "apikey": serviceKey, "Authorization": `Bearer ${serviceKey}` }
  })
  const trades = await res.json()
  if (!trades || trades.length === 0) return NextResponse.json({ error: "No trades" }, { status: 400 })

  const totalPnL = trades.reduce((a: number, t: any) => a + (t.pnl || 0), 0)
  const wins = trades.filter((t: any) => t.pnl > 0).length
  const winRate = ((wins / trades.length) * 100).toFixed(1)
  const now = new Date().toISOString().split("T")[0]

  // ─── TXT Export ──────────────────────────────────────
  if (format === "txt") {
    let txt = "═══════════════════════════════════════════\n"
    txt += "           TRADEVAULT TRADING REPORT\n"
    txt += "═══════════════════════════════════════════\n\n"
    txt += `Generated: ${now}\n`
    txt += `Total Trades: ${trades.length}\n`
    txt += `Winning: ${wins} | Losing: ${trades.length - wins}\n`
    txt += `Win Rate: ${winRate}%\n`
    txt += `Total P&L: $${totalPnL.toFixed(2)}\n\n`
    txt += "───────────────────────────────────────────\n"
    txt += "TRADE DETAILS\n"
    txt += "───────────────────────────────────────────\n\n"
    trades.forEach((t: any, i: number) => {
      txt += `#${i + 1}  ${t.asset} | ${t.direction} | Entry: $${t.entry} | Exit: $${t.close_price} | P&L: $${(t.pnl||0).toFixed(2)} | ${t.emotion||"N/A"} | ${t.created_at?.split("T")[0]}\n`
    })
    txt += "\n═══════════════════════════════════════════\n"
    txt += "       Generated by TradeVault.pro\n"
    txt += "═══════════════════════════════════════════\n"

    return new NextResponse(txt, {
      headers: { "Content-Type": "text/plain", "Content-Disposition": `attachment; filename="TradeVault_Report_${now}.txt"` }
    })
  }

  // ─── CSV Export ──────────────────────────────────────
  if (format === "csv") {
    let csv = "Trade #,Asset,Direction,Entry Price,Exit Price,Size,P&L,Emotion,Date\n"
    trades.forEach((t: any, i: number) => {
      csv += `${i+1},"${t.asset}","${t.direction}",${t.entry},${t.close_price},${t.original_size||t.size},${(t.pnl||0).toFixed(2)},"${t.emotion||""}","${t.created_at?.split("T")[0]}"\n`
    })
    return new NextResponse(csv, {
      headers: { "Content-Type": "text/csv", "Content-Disposition": `attachment; filename="TradeVault_Trades_${now}.csv"` }
    })
  }

  // ─── PDF Export (Premium) ────────────────────────────
  if (format === "pdf") {
    // Generate clean HTML table for PDF
    let rows = ""
    trades.forEach((t: any, i: number) => {
      const pnlClass = (t.pnl||0) >= 0 ? "color:#22c55e" : "color:#ef4444"
      rows += `<tr style="border-bottom:1px solid #333">
        <td style="padding:8px">${i+1}</td>
        <td style="padding:8px;font-weight:bold">${t.asset}</td>
        <td style="padding:8px">${t.direction}</td>
        <td style="padding:8px">$${t.entry}</td>
        <td style="padding:8px">$${t.close_price}</td>
        <td style="padding:8px">${t.original_size||t.size}</td>
        <td style="padding:8px;font-weight:bold;${pnlClass}">$${(t.pnl||0).toFixed(2)}</td>
        <td style="padding:8px">${t.emotion||"-"}</td>
      </tr>`
    })

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>TradeVault Report</title>
    <style>body{font-family:Arial,sans-serif;background:#111;color:#eee;padding:40px}
    h1{color:#eab308;text-align:center;font-size:24px;margin-bottom:5px}
    .subtitle{text-align:center;color:#888;margin-bottom:30px;font-size:12px}
    .summary{display:flex;justify-content:center;gap:30px;margin-bottom:30px;flex-wrap:wrap}
    .stat{text-align:center;background:#1a1a1a;padding:15px 20px;border-radius:10px;border:1px solid #333}
    .stat .value{font-size:22px;font-weight:bold;color:#eab308}
    .stat .label{font-size:11px;color:#888;margin-top:3px}
    table{width:100%;border-collapse:collapse;margin-top:20px}
    th{background:#1a1a1a;padding:10px;text-align:left;font-size:11px;color:#888;text-transform:uppercase;border-bottom:2px solid #eab308}
    td{font-size:13px}
    .footer{text-align:center;margin-top:40px;color:#555;font-size:10px}
</style></head><body>
<h1>TRADEVAULT</h1><p class="subtitle">Professional Trading Report · Generated ${now}</p>
<div class="summary">
<div class="stat"><div class="value">${trades.length}</div><div class="label">Total Trades</div></div>
<div class="stat"><div class="value">${winRate}%</div><div class="label">Win Rate</div></div>
<div class="stat"><div class="value">$${totalPnL.toFixed(2)}</div><div class="label">Total P&L</div></div>
<div class="stat"><div class="value">${wins}W / ${trades.length-wins}L</div><div class="label">Record</div></div>
</div>
<table><thead><tr><th>#</th><th>Asset</th><th>Dir</th><th>Entry</th><th>Exit</th><th>Size</th><th>P&L</th><th>Emotion</th></tr></thead><tbody>${rows}</tbody></table>
<p class="footer">Generated by TradeVault.pro · Professional Trading Analytics</p>
</body></html>`

    return new NextResponse(html, {
      headers: { "Content-Type": "text/html", "Content-Disposition": `attachment; filename="TradeVault_Report_${now}.html"` }
    })
  }

  return NextResponse.json({ error: "Invalid format" }, { status: 400 })
}